site_name: meow
repo_url: https://github.com/flaport/meow
site_url: https://flaport.github.io/meow
site_description: Modeling of Eigenmodes and Overlaps in Waveguides
site_author: Floris Laporte
repo_name: flaport/meow
copyright: Copyright © 2025, Floris Laporte, Apache-2.0

theme:
  name: shadcn
  logo: assets/logo-small.svg
  favicon: assets/logo-small.ico
  katex_options: {}
  crossref_modules:
    - meow
    - meow.eme
    - meow.fde
  crossref_aliases:
    compute_modes: meow.compute_modes_tidy3d
    compute_s_matrix: meow.compute_s_matrix_sax

nav:
  - home: index.md
  - quickstart: nbs/00_introduction.md
  - examples:
      - from gds: nbs/01_gds_taper.md
      - taper length sweep: nbs/02_taper_length_sweep.md
      - different modes: nbs/03_unequal_number_of_modes.md
      - rib interface: nbs/04_rib_interface.md
      - mode propagation: nbs/05_propagate_modes.md
  - algorithm: algorithm.md
  - api: api.md
  - changelog: changelog.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          inventories:
            - https://docs.jax.dev/en/latest/objects.inv
            - https://docs.kidger.site/jaxtyping/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://docs.xarray.dev/en/stable/objects.inv
            - https://flaport.github.io/sax/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://python-markdown.github.io/objects.inv
            - https://scipy.github.io/devdocs/objects.inv
            - https://typing.readthedocs.io/en/latest/objects.inv
            - https://www.mkdocs.org/objects.inv
